name: "[ubuntu-wsl] Execution"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install zsh
      run: sudo apt-get install -y zsh

    - name: Execute init.sh
      run: source ${GITHUB_WORKSPACE}/ubuntu-wsl/init.sh
      shell: zsh {0}
