name: "[ubuntu-wsl] Execution"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Execute init.sh
      run: ${GITHUB_WORKSPACE}/ubuntu-wsl/init.sh

    - name: Execute on_zsh.sh
      run: ${GITHUB_WORKSPACE}/ubuntu-wsl/scripts/on_zsh.sh
      shell: zsh
