name: "[ubuntu-wsl] Execution"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install zsh & VSCode
      run: |
        sudo apt-get install -y zsh
        zsh --version
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        sudo apt update
        sudo apt install code
        code --version

    - name: Execute init.sh (without VSCode)
      run: |
        export VSCODE_PATH=""
        export GIT_CREDENTIAL_MANAGER=""
        . ${GITHUB_WORKSPACE}/ubuntu-wsl/init.sh
      shell: zsh {0}
