name: "ubuntu-wsl"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check init.sh
        run: shellcheck ${GITHUB_WORKSPACE}/ubuntu-wsl/init.sh

      - name: Check **/symlink.sh
        run: shellcheck ${GITHUB_WORKSPACE}/ubuntu-wsl/**/symlink.sh

      - name: Check scripts/apt_install.sh
        run: shellcheck ${GITHUB_WORKSPACE}/ubuntu-wsl/scripts/apt_install.sh

      - name: Check scripts/install.sh
        run: shellcheck ${GITHUB_WORKSPACE}/ubuntu-wsl/scripts/install.sh

  script-execution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install zsh & VSCode
      run: |
        sudo apt-get install -y zsh
        zsh --version
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        sudo apt update
        sudo apt install code
        code --version

    - name: Execute init.sh
      run: |
        export VSCODE_PATH=""
        . ${GITHUB_WORKSPACE}/ubuntu-wsl/init.sh
      shell: zsh {0}
